# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from xbox_input_pub/xbox_input.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class xbox_input(genpy.Message):
  _md5sum = "147af40cd5ad08adffe12a6229afa770"
  _type = "xbox_input_pub/xbox_input"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 vx
float64 vy
float64 wz
float64 pit 
time timestamps
bool conf 
"""
  __slots__ = ['vx','vy','wz','pit','timestamps','conf']
  _slot_types = ['float64','float64','float64','float64','time','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vx,vy,wz,pit,timestamps,conf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(xbox_input, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.wz is None:
        self.wz = 0.
      if self.pit is None:
        self.pit = 0.
      if self.timestamps is None:
        self.timestamps = genpy.Time()
      if self.conf is None:
        self.conf = False
    else:
      self.vx = 0.
      self.vy = 0.
      self.wz = 0.
      self.pit = 0.
      self.timestamps = genpy.Time()
      self.conf = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d2IB().pack(_x.vx, _x.vy, _x.wz, _x.pit, _x.timestamps.secs, _x.timestamps.nsecs, _x.conf))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamps is None:
        self.timestamps = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 41
      (_x.vx, _x.vy, _x.wz, _x.pit, _x.timestamps.secs, _x.timestamps.nsecs, _x.conf,) = _get_struct_4d2IB().unpack(str[start:end])
      self.conf = bool(self.conf)
      self.timestamps.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d2IB().pack(_x.vx, _x.vy, _x.wz, _x.pit, _x.timestamps.secs, _x.timestamps.nsecs, _x.conf))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamps is None:
        self.timestamps = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 41
      (_x.vx, _x.vy, _x.wz, _x.pit, _x.timestamps.secs, _x.timestamps.nsecs, _x.conf,) = _get_struct_4d2IB().unpack(str[start:end])
      self.conf = bool(self.conf)
      self.timestamps.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d2IB = None
def _get_struct_4d2IB():
    global _struct_4d2IB
    if _struct_4d2IB is None:
        _struct_4d2IB = struct.Struct("<4d2IB")
    return _struct_4d2IB
